title: GitLab and [x]
description:  GitLab and Git for Project Management, Collaboration besides Code, and combined with [YOUR TOOL] 
theme: just-the-docs

url: https://s4b7r.github.io/gitlab-and-x

aux_links:
  Template Repository: https://github.com/s4b7r/gitlab-and-x
